BOT_TOKEN = "7585054657:AAEblTYuvk7tJgr4wu3TOfDF9uMB6SrvpUM" #Token of your bot
CHAT_ID =  "" # chat-id of your telegram-account
RTSP_URL = 0 # Use rtsp-url of your camera. 0 for web-camera
DB_NAME = "postgres" # Name of your database
PASSWORD = "" # Password of your database
USERNAME = "postgres" # Your username
HOST = "localhost" # Your host
FRAMES_FROM_VIDEOS = r"C:\Users\user\Pictures" #You can change them to any other directory
UNKNOWN_FACES = r"C:\Users\user\Pictures\unknown_faces"